name: hw-aeson
version: '0.1.0.0'
category: Data, JSON
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2018 John Ky
license: BSD3
github: haskell-works/hw-aeson
synopsis: Convenience functions for Aeson
description: Convenience functions for Aeson

extra-source-files:
- README.md

dependencies:
- aeson

library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Data.Aeson
  dependencies:
  - base >=4.7 && <5
  - text

tests:
  hw-aeson-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hspec
    - hedgehog
    - hw-aeson
